apiVersion: v1
kind: Pod
metadata:
  name: nginx-test-pod
  namespace: casino
spec:
  containers:
    - name: test-container
      image: nginx
      envFrom:
      - configMapRef:
          name: game-config-2
  restartPolicy: Never