apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: casino
  labels:
    app: nginx
    env: dev
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80