apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  namespace: casino
  labels:
    app: tomcat
    env: dev
spec:
  selector:
    app: tomcat
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080