apiVersion: v1
kind: Pod
metadata:
  name: nginx-casino-dev
  namespace: casino
  labels:
    env: dev
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80

---

apiVersion: v1
kind: Pod
metadata:
  name: nginx-casino-cert
  namespace: casino
  labels:
    env: cert
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80