apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
#Cuando un PersistentVolumeClaim (PVC) se elimina, el PV que respalda el PVC no se elimina. Los datos en el PV se mantienen tal como están
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /tmp/data

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: nginx
    volumeMounts:
    - name: my-volume
      mountPath: /usr/share/nginx/html
  volumes:
  - name: my-volume
    persistentVolumeClaim:
      claimName: my-pvc

---

apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod
spec:
  volumes:
    - name: my-volume
      persistentVolumeClaim:
        claimName: my-pvc
  containers:
    - name: busybox
      image: busybox
      volumeMounts:
        - name: my-volume
          mountPath: /usr/share/nginx/html
      command: ["/bin/sh", "-c"]
      args:
        - while true; do
            date >> /usr/share/nginx/html/index.html;
            sleep 10;
          done