namespace: comisaria
properties:
  - name: SERVER_PORT
    value: 80
#  - name: SPRING_PROFILES_ACTIVE
#    value: dev
secret:
  - name: SPRING_DATA_MONGODB_URI
    value: bW9uZ29kYitzcnY6Ly9zYWludHdpbDp6MzFBYTdtM2dqa01wdHVzQGNsdXN0ZXIwLm5tcThnZzkubW9uZ29kYi5uZXQvY29taXNhcmlhP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eSZhcHBOYW1lPUNsdXN0ZXIw
deployment:
  replicaCount: 2
  # imagePullSecretsName: ""
  # labels:
  #   action: custom
  #   demo: demo01
image:
  imageRegistry: wlopezob
  tag: latest
  port: 80

env: prod

resources_plan:
  cpu_limits: 0.5
  cpu_requests: 40m
  memory_limits: 512M
  memory_requests: 256M

service:
  type: ClusterIP
  servicePort: 80
  targetPort: 80
ingress:
  path: /app-database/v1
  #targetPath: /app-database/v1
  pathType: ImplementationSpecific
  port: 80
