apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: casino
  labels:
    app: nginx
    env: dev
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
