apiVersion: v1
kind: ConfigMap
immutable: true
metadata:
    name: {{.Release.Name}}
    namespace: {{ $.Values.namespace | default "default" }}
data:
    {{- range $index, $map := $.Values.properties }}
    {{ $map.name }}: {{ $map.value | quote}}
    {{- end }}