apiVersion: v1
kind: Secret
metadata:
  name: {{.Release.Name}}
  namespace: {{ $.Values.namespace | default "default" }}
data:
    {{- range $index, $map := $.Values.secret }}
    {{ $map.name }}: {{ $map.value | quote}}
    {{- end }}